### ISSUE TITLE
[ Question ] Could this port be adopted to work in 1.8.9

### ISSUE THREAD

**Issue by Letus252** [DarkShadow44/DistantHorizonsStandalone#105]
This is not an issue, but I couldn't find an answer anywhere. I'm not sure if there is any demand for this version, I've been out of pvp/minigames 1.8.9 community for a many years, but at some point it was very large. 

I'm not asking somebody to make it, I'm just wondering how feasible it is. Jump from 1.7.10 to 1.8.9 does not seem large, and when I tried this version in 1.8.9, it fails with `java.lang.NoClassDefFoundError: com/gtnewhorizon/gtnhmixins/IEarlyMixinLoader`  (missing dependency?).

**Comment by DarkShadow44** [comment]
First, you can't just run a 1.7.10 mod in 1.8.9, this won't work at all. I'm currently working on merging 1.7.10 support into the official DistantHorizons, it already has 1.12.2 version by Karnatour based on my port, so there's that.

A user on discord asked "is DH for 1.8.9 also in plans?". Karnatour replied "yes its my next go to version"

So it looks like 1.8.9 is coming! For more info and if you want to help you can visit the official DistantHorizons discord.

**Comment by Letus252** [comment]
> First, you can't just run a 1.7.10 mod in 1.8.9, this won't work at all. I'm currently working on merging 1.7.10 support into the official DistantHorizons, it already has 1.12.2 version by Karnatour based on my port, so there's that.
> 
> A user on discord asked "is DH for 1.8.9 also in plans?". Karnatour replied "yes its my next go to version"
> 
> So it looks like 1.8.9 is coming! For more info and if you want to help you can visit the official DistantHorizons discord.

Thank you, I will take a look.
